// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPUm23gHCQ337VlkCk8izizp1ijA_mzg',
    appId: '1:451365722493:web:d8abb0bcdbd8ddc7435414',
    messagingSenderId: '451365722493',
    projectId: 'aurasense-920b6',
    authDomain: 'aurasense-920b6.firebaseapp.com',
    storageBucket: 'aurasense-920b6.firebasestorage.app',
    measurementId: 'G-QDE076K1Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVH-7pfliJkD2lpYvqTjvLd4ee4H2tIjA',
    appId: '1:994167549091:android:522692cb2f8c872aaea316',
    messagingSenderId: '994167549091',
    projectId: 'alarm-145d1',
    databaseURL: 'https://alarm-145d1-default-rtdb.firebaseio.com',
    storageBucket: 'alarm-145d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAViXgvZ2ITaet8n7XJk9KC0MktkX0a39M',
    appId: '1:994167549091:ios:aa9898b4e86adbb2aea316',
    messagingSenderId: '994167549091',
    projectId: 'alarm-145d1',
    databaseURL: 'https://alarm-145d1-default-rtdb.firebaseio.com',
    storageBucket: 'alarm-145d1.firebasestorage.app',
    iosBundleId: 'com.aurasense.app',
  );

}